version: "3"

services:

  todotests:
   
    image: todotests
    restart: on-failure
    environment:
      - DB_HOST=database
    depends_on:
      - "todofront"
      - "todoback"

  todofront:
    image: todofrontend
    restart: on-failure
    ports:
      - 3000:3000
    environment:
      - DB_HOST_BACK=todoback
    depends_on:
      - "todoback"
    
  todoback:
    image: todobackend
    restart: on-failure
    ports:
      - 3001:3001
    
   
  
  